# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  target 'Fringe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fringe
  pod 'AssistantKit', '~> 0.6.1'
  pod 'IQKeyboardManagerSwift', '~> 6.5.1'
  pod 'Localize-Swift', '~> 3.1.0'
  pod 'Alamofire'
  pod 'lottie-ios', '~> 3.1.6'
  pod 'SDWebImage', '~> 4.4.5'
  pod 'KRPullLoader'
  pod 'UITextView+Placeholder', '~> 1.4.0'
  pod 'pop', '~> 1.0.12'
  pod 'Toucan'
  pod "MonthYearPicker", '~> 4.0.2'
  pod 'GCCountryPicker'
  pod 'FSCalendar'
  pod 'SVProgressHUD'

  #facebook sign in
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  #google sign in
  pod 'GoogleSignIn'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  #Home Screen pull up
  pod 'FittedSheets'
  
  #apple sign in
  pod 'AppleSignIn'

  # payment
  pod 'Stripe'
  pod "TimeZoneLocate"
  pod 'PayPalCheckout'
  
  # Firebase
  pod 'Firebase'
  pod 'Firebase/Crashlytics'
   
  # Messages
  pod 'MessageKit', '~> 3.6.0' #Swift 4.2
  pod 'MessageInputBar', '~> 0.4.1'
  pod 'Kingfisher', '~> 7.0'  

  # Socket
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  
  # Country Picker
  pod 'SKCountryPicker'


end
