# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  target 'Fringe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fringe
  pod 'AssistantKit', '~> 0.6.1'
  pod 'IQKeyboardManagerSwift', '~> 6.5.1'
  pod 'Localize-Swift', '~> 3.1.0'
  pod 'Alamofire', '~> 4.8.1'
  pod 'lottie-ios', '~> 3.1.6'
  pod 'SDWebImage', '~> 4.4.5'
  pod 'KRPullLoader'
  pod 'UITextView+Placeholder', '~> 1.4.0'
  pod 'pop', '~> 1.0.12'
  pod 'Toucan'
  pod "MonthYearPicker", '~> 4.0.2'
  pod 'GCCountryPicker'
  pod 'FSCalendar'

  #google sign in
  pod 'GoogleSignIn'

  #Home Screen pull up
  pod 'FittedSheets'
  
  #apple sign in
  pod 'AppleSignIn'

  # payment
  pod 'Stripe'
  pod "TimeZoneLocate"
  
  # Firebase
  pod 'Firebase'
  pod 'Firebase/Crashlytics'

end
